---
# tasks file for mbreisch.ufw-role

- name: Ensure ufw is installed
  apt: name=ufw state=latest update_cache=yes

- name: Configure ufw defaults
  ufw: direction={{ item.direction }} policy={{ item.policy }}
  with_items:
    - { direction: 'incoming', policy: 'reject' }
    - { direction: 'outgoing', policy: 'allow' }
  notify:
    - reload ufw

- name: Configure IPV6
  lineinfile: dest=/etc/default/ufw
              regexp="^IPV6="
              line="IPV6={{ ufw_allow_ipv6 | default('no')  }} "
              state=present
  notify: reload ufw

- name: Configure minimal ufw rules
  ufw: rule={{ item.rule }} port={{ item.port }} proto={{ item.proto }} from={{ item.from }}
  with_items: "{{ ufw_minimal_rules }}"
  notify:
    - reload ufw

- name: Configure extra ufw rules for {{ ufw_callable_role | default('undefined...skipping...') }}
  ufw: rule={{ item.rule }} port={{ item.port }} proto={{ item.proto }} from={{ item.from }}
  with_items: "{{ ufw_role_rules | default([]) }}"
  notify:
    - reload ufw

- name: Enable ufw logging
  ufw: logging=on
  notify:
    - reload ufw

- name: Enable ufw
  ufw: state=enabled